import os
import json
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.image as mpimg

def create_pdf_report(
    project_dir=r"C:\Users\sanja\Downloads\role1_simulated_handoff",
    pdf_filename="Acoustic_FMCW_Radar_Simulation_Graphs.pdf"
):
    pdf_path_outputs = os.path.join(project_dir, "outputs", pdf_filename)
    pdf_path_root = os.path.join(project_dir, pdf_filename)
    plots_dir = os.path.join(project_dir, "plots")
    
    with open(os.path.join(project_dir, "config.json"), "r") as f:
        config = json.load(f)
    with open(os.path.join(project_dir, "outputs", "results.json"), "r") as f:
        results = json.load(f)

    with PdfPages(pdf_path_outputs) as pdf:
        # =========================================================================
        # PAGE 1: Title & Executive Summary Table
        # =========================================================================
        fig = plt.figure(figsize=(11, 8.5))
        fig.patch.set_facecolor("#f8f9fa")
        
        plt.subplot2grid((12, 12), (0, 0), rowspan=2, colspan=12)
        plt.axis("off")
        plt.text(0.5, 0.65, "Acoustic FMCW Radar — Vital Sign Tracking Simulation",
                 ha="center", va="center", fontsize=18, fontweight="bold", color="#0f2b48")
        plt.text(0.5, 0.20, "Comprehensive DSP Analysis, Range Profiling, Stress Tests & Benchmark Report",
                 ha="center", va="center", fontsize=11, color="#495057", style="italic")
        
        plt.subplot2grid((12, 12), (2, 0), rowspan=4, colspan=12)
        plt.axis("off")
        box_text = (
            "SYSTEM & RADAR PARAMETERS:\n"
            f"• Sampling Frequency: {config['role1_to_role2_contract']['sample_rate_hz']} Hz   |   "
            f"• Chirp Bandwidth: {config['fmcw']['bandwidth_hz']/1e3:.1f} kHz ({config['fmcw']['f_start_hz']/1e3:.1f} - {config['fmcw']['f_end_hz']/1e3:.1f} kHz)\n"
            f"• Chirp Duration Tc: {config['fmcw']['chirp_duration_s']*1e3:.0f} ms   |   "
            f"• Frame Interval Tframe: {(config['fmcw']['chirp_duration_s']+config['fmcw']['gap_duration_s'])*1e3:.0f} ms   |   "
            f"• Chirps: {config['fmcw']['num_chirps']} (9.0 s duration)\n"
            f"• Speed of Sound: {config['synthetic_target']['speed_of_sound_mps']} m/s   |   "
            f"• Carrier Center Frequency fc: {(config['fmcw']['f_start_hz']+config['fmcw']['bandwidth_hz']/2)/1e3:.2f} kHz   |   "
            f"• Wavelength lambda: {(config['synthetic_target']['speed_of_sound_mps']/(config['fmcw']['f_start_hz']+config['fmcw']['bandwidth_hz']/2))*1e3:.2f} mm"
        )
        plt.text(0.02, 0.5, box_text, fontsize=10, family="monospace", va="center",
                 bbox=dict(boxstyle="round,pad=0.8", facecolor="#e9ecef", edgecolor="#ced4da", lw=1.5))
        
        plt.subplot2grid((12, 12), (6, 0), rowspan=5, colspan=12)
        plt.axis("off")
        
        table_data = [
            ["Metric", "Reference Truth", "Primary Dataset (Original)", "Continuous Delay Model", "Status"],
            ["Target Range (R)", f"{config['synthetic_target']['nominal_range_m']:.2f} m", "1.0004 m (Error: 0.42 mm)", "1.0004 m", "SUCCESS"],
            ["Beat Frequency (fb)", "174.93 Hz", "175.00 Hz", "175.00 Hz", "SUCCESS"],
            ["Respiration Rate", f"{results['respiration']['reference_bpm']:.1f} BPM", f"{results['respiration']['estimated_bpm']:.2f} BPM (Error: {results['respiration']['error_bpm']:.2f} BPM)", "14.63 BPM", "SUCCESS"],
            ["Respiration Amplitude", f"{results['respiration']['reference_amplitude_mm']:.1f} mm", f"{results['respiration']['estimated_amplitude_mm']:.2f} mm", "4.74 mm", "SUCCESS"],
            ["Cardiac Heart Rate", f"{results['cardiac']['reference_bpm']:.1f} BPM", "Degraded (Quantized Steps)", f"72.07 BPM (Error: 0.07 BPM)", "BENCHMARK OK"],
            ["Cardiac Amplitude", f"{results['cardiac']['reference_amplitude_mm']:.2f} mm", "Step Noise Artifact", "0.150 mm", "BENCHMARK OK"]
        ]
        
        table = plt.table(cellText=table_data, loc="center", cellLoc="center")
        table.auto_set_font_size(False)
        table.set_fontsize(10)
        table.scale(1, 1.8)
        
        for (row, col), cell in table.get_celld().items():
            if row == 0:
                cell.set_facecolor("#1f77b4")
                cell.set_text_props(color="white", fontweight="bold")
            else:
                cell.set_facecolor("#ffffff" if row % 2 == 0 else "#f1f3f5")
                if col == 4:
                    if "SUCCESS" in cell.get_text().get_text():
                        cell.set_text_props(color="#2ca02c", fontweight="bold")
                    else:
                        cell.set_text_props(color="#0055aa", fontweight="bold")

        plt.subplot2grid((12, 12), (11, 0), rowspan=1, colspan=12)
        plt.axis("off")
        plt.text(0.5, 0.2, "Generated by Acoustic FMCW Radar Simulation DSP Pipeline | Page 1 of 6",
                 ha="center", va="center", fontsize=9, color="#6c757d")
        
        plt.tight_layout()
        pdf.savefig(fig, dpi=300)
        plt.close()

        # =========================================================================
        # PAGE 2: Role 1 — Acoustic FMCW Transmission & Reception
        # =========================================================================
        fig = plt.figure(figsize=(11, 8.5))
        plt.suptitle("Role 1: Simulated Acoustic FMCW Transmission & Reception", fontsize=15, fontweight="bold", y=0.97)
        
        ax1 = fig.add_subplot(2, 2, 1)
        ax1.imshow(mpimg.imread(os.path.join(plots_dir, "tx_chirp.png")))
        ax1.axis("off")
        ax1.set_title("1. Transmitted FMCW Chirp Signal (18-21 kHz)", fontsize=11, fontweight="bold")

        ax2 = fig.add_subplot(2, 2, 2)
        ax2.imshow(mpimg.imread(os.path.join(plots_dir, "rx_audio.png")))
        ax2.axis("off")
        ax2.set_title("2. Received Acoustic Signal (60 Chirp Frames)", fontsize=11, fontweight="bold")

        ax3 = fig.add_subplot(2, 1, 2)
        ax3.imshow(mpimg.imread(os.path.join(plots_dir, "spectrogram.png")))
        ax3.axis("off")
        ax3.set_title("3. Time-Frequency Spectrogram (STFT)", fontsize=11, fontweight="bold")

        fig.text(0.5, 0.02, "Acoustic FMCW Radar Simulation Report | Page 2 of 6", ha="center", fontsize=9, color="#6c757d")
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        pdf.savefig(fig, dpi=300)
        plt.close()

        # =========================================================================
        # PAGE 3: Role 2 — FMCW Radar DSP & Range Profiling
        # =========================================================================
        fig = plt.figure(figsize=(11, 8.5))
        plt.suptitle("Role 2: FMCW Radar Signal Processing & Range Profile", fontsize=15, fontweight="bold", y=0.97)

        ax1 = fig.add_subplot(2, 1, 1)
        ax1.imshow(mpimg.imread(os.path.join(plots_dir, "range_profile.png")))
        ax1.axis("off")
        ax1.set_title("4. Fast-Time FFT Range Profile [R = c * f_beat * Tc / (2B)] & Slow-Time Heatmap", fontsize=11, fontweight="bold")

        ax2 = fig.add_subplot(2, 1, 2)
        ax2.imshow(mpimg.imread(os.path.join(plots_dir, "target_bin_magnitude.png")))
        ax2.axis("off")
        ax2.set_title("5. Target Range Bin Magnitude vs Slow-Time Chirps", fontsize=11, fontweight="bold")

        fig.text(0.5, 0.02, "Acoustic FMCW Radar Simulation Report | Page 3 of 6", ha="center", fontsize=9, color="#6c757d")
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        pdf.savefig(fig, dpi=300)
        plt.close()

        # =========================================================================
        # PAGE 4: Role 3 — Vital Sign Extraction (Primary Dataset)
        # =========================================================================
        fig = plt.figure(figsize=(11, 8.5))
        plt.suptitle("Role 3: Vital Sign Extraction & Phase Analysis (Primary Dataset)", fontsize=15, fontweight="bold", y=0.97)

        ax1 = fig.add_subplot(2, 2, 1)
        ax1.imshow(mpimg.imread(os.path.join(plots_dir, "target_phase.png")))
        ax1.axis("off")
        ax1.set_title("6. Wrapped vs Unwrapped Phase", fontsize=10, fontweight="bold")

        ax2 = fig.add_subplot(2, 2, 2)
        ax2.imshow(mpimg.imread(os.path.join(plots_dir, "displacement.png")))
        ax2.axis("off")
        ax2.set_title("7. Chest Displacement Waveform", fontsize=10, fontweight="bold")

        ax3 = fig.add_subplot(2, 2, 3)
        ax3.imshow(mpimg.imread(os.path.join(plots_dir, "respiration_spectrum.png")))
        ax3.axis("off")
        ax3.set_title("8. Respiration Waveform & Spectrum", fontsize=10, fontweight="bold")

        ax4 = fig.add_subplot(2, 2, 4)
        ax4.imshow(mpimg.imread(os.path.join(plots_dir, "cardiac_spectrum.png")))
        ax4.axis("off")
        ax4.set_title("9. Cardiac Waveform & Spectrum", fontsize=10, fontweight="bold")

        fig.text(0.5, 0.02, "Acoustic FMCW Radar Simulation Report | Page 4 of 6", ha="center", fontsize=9, color="#6c757d")
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        pdf.savefig(fig, dpi=300)
        plt.close()

        # =========================================================================
        # PAGE 5: Scientific Benchmark — Continuous Fractional-Delay Model
        # =========================================================================
        fig = plt.figure(figsize=(11, 8.5))
        plt.suptitle("Scientific Benchmark: Continuous Fractional-Delay Model (Micro-Motion Recovery)", fontsize=14, fontweight="bold", y=0.97)

        imp_plots_dir = os.path.join(plots_dir, "improved_model")
        
        ax1 = fig.add_subplot(2, 2, 1)
        ax1.imshow(mpimg.imread(os.path.join(imp_plots_dir, "target_phase.png")))
        ax1.axis("off")
        ax1.set_title("10. True Continuous Sinusoidal Phase", fontsize=10, fontweight="bold")

        ax2 = fig.add_subplot(2, 2, 2)
        ax2.imshow(mpimg.imread(os.path.join(imp_plots_dir, "displacement.png")))
        ax2.axis("off")
        ax2.set_title("11. Continuous Chest Displacement", fontsize=10, fontweight="bold")

        ax3 = fig.add_subplot(2, 2, 3)
        ax3.imshow(mpimg.imread(os.path.join(imp_plots_dir, "respiration_spectrum.png")))
        ax3.axis("off")
        ax3.set_title("12. Recovered Respiration Spectrum (14.63 BPM)", fontsize=10, fontweight="bold")

        ax4 = fig.add_subplot(2, 2, 4)
        ax4.imshow(mpimg.imread(os.path.join(imp_plots_dir, "cardiac_spectrum.png")))
        ax4.axis("off")
        ax4.set_title("13. Recovered Cardiac Spectrum (72.07 BPM)", fontsize=10, fontweight="bold")

        fig.text(0.5, 0.02, "Acoustic FMCW Radar Simulation Report | Page 5 of 6", ha="center", fontsize=9, color="#6c757d")
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        pdf.savefig(fig, dpi=300)
        plt.close()

        # =========================================================================
        # PAGE 6: Advanced Tests — Noise Robustness, Motion Artifacts & Forensic PSD
        # =========================================================================
        fig = plt.figure(figsize=(11, 8.5))
        plt.suptitle("Advanced DSP Tests: Noise Robustness, Motion Artifacts & Forensic Comparison", fontsize=14, fontweight="bold", y=0.97)

        ax1 = fig.add_subplot(2, 2, 1)
        if os.path.exists(os.path.join(plots_dir, "noise_robustness_comparison.png")):
            ax1.imshow(mpimg.imread(os.path.join(plots_dir, "noise_robustness_comparison.png")))
        ax1.axis("off")
        ax1.set_title("14. Complex AWGN Noise Robustness (30-5 dB SNR)", fontsize=10, fontweight="bold")

        ax2 = fig.add_subplot(2, 2, 2)
        if os.path.exists(os.path.join(plots_dir, "dataset_forensic_comparison.png")):
            ax2.imshow(mpimg.imread(os.path.join(plots_dir, "dataset_forensic_comparison.png")))
        ax2.axis("off")
        ax2.set_title("15. Forensic Power Spectral Density (PSD) Comparison", fontsize=10, fontweight="bold")

        ax3 = fig.add_subplot(2, 1, 2)
        if os.path.exists(os.path.join(plots_dir, "motion_artifact_mitigation.png")):
            ax3.imshow(mpimg.imread(os.path.join(plots_dir, "motion_artifact_mitigation.png")))
        ax3.axis("off")
        ax3.set_title("16. Motion Artifact Detection & Adaptive Mitigation", fontsize=10, fontweight="bold")

        fig.text(0.5, 0.02, "Acoustic FMCW Radar Simulation Report | Page 6 of 6", ha="center", fontsize=9, color="#6c757d")
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        pdf.savefig(fig, dpi=300)
        plt.close()

    import shutil
    shutil.copy2(pdf_path_outputs, pdf_path_root)
    print(f"PDF generated successfully at:\n  1. {pdf_path_outputs}\n  2. {pdf_path_root}")

if __name__ == "__main__":
    create_pdf_report()
